#!/bin/bash
# Deterministic openXC7 build: ASLR off (setarch -R) so nextpnr's pointer-hashed
# placement is reproducible run-to-run, + PYTHONHASHSEED=0 for migen/floorplan.
# Without ASLR off, the SAME seed thrashes one run and places fine the next.
#
# DANTE PHASE 0.5: the ROM image is the frozen LOADER, not the application
# firmware. Firmware now lives in coderam and is delivered at runtime:
#
#   firmware/loader/  -> baked into the 12 KB BRAM ROM (this build)
#   firmware/         -> pushed over Ethernet with tools/netload.py, or from
#                        SPI flash, WITHOUT rebuilding the bitstream
#
# So a firmware change no longer re-rolls P&R placement. Rebuild the bitstream
# only when the gateware or the loader changes.
#
# For a standalone single-image bitstream (no loader, no runtime load):
#   ./build.sh --bake-firmware --firmware firmware/firmware.bin
set -e

export CHIPDB=/home/lisp/FPGA/demo-projects/chipdb
export PRJXRAY_DB_DIR=/home/lisp/openxc7/openxc7/opt/nextpnr-xilinx/external/prjxray-db
export PYTHONHASHSEED=0

HERE="$(cd "$(dirname "$0")" && pwd)"

# Default ROM image = the loader, unless the caller overrides --firmware.
ROM_IMAGE_ARGS=()
if [[ ! " $* " =~ " --firmware " ]]; then
    LOADER="$HERE/firmware/loader/loader.bin"
    if [[ ! -f "$LOADER" ]]; then
        echo "error: $LOADER not found. Build it first:" >&2
        echo "         make -C firmware/loader" >&2
        exit 1
    fi
    ROM_IMAGE_ARGS=(--firmware "$LOADER")

    # The loader is COMPILED AGAINST generated/csr.h and BAKED INTO the ROM, so
    # any gateware change that moves a CSR address silently invalidates it: the
    # bitstream builds clean, flashes fine, and the loader then pokes registers
    # that have moved. This has cost a debugging session FOUR times now --
    # adding LiteScope shifted the addresses once, removing it shifted them back.
    #
    # Rebuild it here so it always tracks the LAST generated csr.h, and record
    # that header's checksum. The post-build check below compares it against the
    # header this run generates; they differ exactly when the loader needs
    # another pass, which is the case that used to pass unnoticed.
    # Honour --output-dir. tools/seed_sweep.sh gives every seed its own build
    # directory, so a hardcoded path here would compare a csr.h that the sweep
    # build never writes -- the guard would sit silently inert on exactly the
    # builds that run unattended.
    OUT_DIR="$HERE/build/colorlight_i9plus"
    prev=""
    for a in "$@"; do
        [[ "$prev" == "--output-dir" ]] && OUT_DIR="$a"
        prev="$a"
    done
    CSR_H="$OUT_DIR/software/include/generated/csr.h"

    # Serialise the loader rebuild. The sweep runs JOBS builds concurrently and
    # they all share firmware/loader/, so three make's racing in one directory
    # can interleave object writes and bake a torn loader into a bitstream whose
    # Fmax then gets recorded as if it meant something.
    ( flock 9 || exit 1
      make -C "$HERE/firmware/loader" >/dev/null 2>&1 ) 9>"$HERE/firmware/loader/.build.lock" || {
        echo "error: loader rebuild failed" >&2; exit 1; }
    # Hash the CSR CONTENT, not the file: LiteX stamps every generated header
    # with "Auto-generated by LiteX (hash) on <date>", so a plain md5sum differs
    # on every single build and the check below would cry wolf every time --
    # which is worse than no check, because a warning that is always wrong gets
    # ignored on the run where it is right.
    csr_fingerprint() { grep -v "Auto-generated by LiteX" "$1" | md5sum | cut -d' ' -f1; }
    CSR_BEFORE=""
    [[ -f "$CSR_H" ]] && CSR_BEFORE=$(csr_fingerprint "$CSR_H")
    trap '
        if [[ -n "$CSR_BEFORE" && -f "$CSR_H" ]]; then
            CSR_AFTER=$(csr_fingerprint "$CSR_H")
            if [[ "$CSR_BEFORE" != "$CSR_AFTER" ]]; then
                echo ""
                echo "*** STALE LOADER *** csr.h CHANGED during this build, so the"
                echo "    loader baked into this bitstream was compiled against the"
                echo "    OLD CSR addresses. DO NOT FLASH IT. Re-run this build:"
                echo "      make -C firmware/loader && ./build.sh $*"
            fi
        fi' EXIT
fi

# HeAP stall watchdog.
#
# Some seeds make nextpnr's analytical placer hang: it prints "Running main
# analytical placer", never prints "HeAP Placer Time", and sits at 100% CPU
# forever. Observed on seed 3, and again on seed 5 after a gateware change --
# that one burned 43 minutes before anyone looked. It is a property of the
# (seed, netlist) pair, so it reappears whenever the gateware or loader changes.
#
# Fail fast instead of hanging. Set STALL_SECS=0 to disable.
#   NOTE: after ANY gateware or loader change, re-sweep with tools/seed_sweep.sh
#   rather than trusting the pinned --seed. The pin is only valid for the
#   netlist it was measured on.
STALL_SECS="${STALL_SECS:-300}"

if [[ "$STALL_SECS" == "0" ]]; then
    exec setarch -R python3 "$HERE/avb_soc.py" --build "${ROM_IMAGE_ARGS[@]}" "$@"
fi

BUILD_LOG="$(mktemp -t infernobuild.XXXXXX.log)"
echo "build log: $BUILD_LOG  (stall watchdog ${STALL_SECS}s)"
setarch -R python3 "$HERE/avb_soc.py" --build "${ROM_IMAGE_ARGS[@]}" "$@" \
    2>&1 | tee "$BUILD_LOG" &
BPID=$!

( while kill -0 "$BPID" 2>/dev/null; do
      sleep 15
      [[ -f "$BUILD_LOG" ]] || continue
      grep -aq "HeAP Placer Time" "$BUILD_LOG" && exit 0   # past the risky phase
      idle=$(( $(date +%s) - $(stat -c %Y "$BUILD_LOG") ))
      if (( idle > STALL_SECS )); then
          echo ""
          echo "*** HeAP STALL: no build output for ${idle}s and HeAP never finished."
          echo "*** This seed does not place on this netlist. Killing."
          echo "*** Try another seed, or run: tools/seed_sweep.sh"
          pkill -9 -f nextpnr-xilinx 2>/dev/null
          kill -9 "$BPID" 2>/dev/null
          exit 1
      fi
  done ) &
WDOG=$!

wait "$BPID" 2>/dev/null
RC=$?
kill "$WDOG" 2>/dev/null
exit $RC
